[package]
name = "core-test"
version = "0.1.0"
authors = [
  "Kang Seonghoon <public+rust@mearie.org>",
  "Brandon W Maister <quodlibetor@gmail.com>",
]
edition = "2018"

[dependencies]
chrono = { path = "../..", default-features = false, features = ["serde"] }

[features]
alloc = ["chrono/alloc"]
